# Generated by Django 4.2 on 2024-12-06 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(db_column='ID_Compra', primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField(blank=True, db_column='Fecha_Compra', null=True)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('precio', models.DecimalField(db_column='Precio', decimal_places=2, max_digits=10)),
                ('monto_total', models.DecimalField(db_column='Monto_Total', decimal_places=2, max_digits=10)),
                ('nivel_calidad', models.CharField(db_column='Nivel_Calidad', max_length=5)),
                ('observacion', models.TextField(blank=True, db_column='Observacion', null=True)),
                ('tipo_pago', models.CharField(db_column='Tipo_Pago', max_length=7)),
            ],
            options={
                'db_table': 'compra',
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id_cuota', models.AutoField(db_column='ID_Cuota', primary_key=True, serialize=False)),
                ('cantidad_cuotas', models.IntegerField(db_column='Cantidad_Cuotas')),
                ('monto', models.DecimalField(db_column='Monto', decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField(db_column='Fecha_Vencimiento')),
                ('estado_pago', models.CharField(blank=True, db_column='Estado_Pago', max_length=10, null=True)),
                ('id_compra', models.ForeignKey(db_column='ID_Compra', on_delete=django.db.models.deletion.DO_NOTHING, to='Front.compra')),
            ],
            options={
                'db_table': 'cuota',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(db_column='ID_Proveedor', primary_key=True, serialize=False)),
                ('dni_pasaporte', models.CharField(db_column='DNI_Pasaporte', max_length=50, unique=True)),
                ('nombre', models.CharField(db_column='Nombre', max_length=255)),
                ('apellidos', models.CharField(db_column='Apellido_Paterno', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=15, null=True)),
                ('correo_electronico', models.CharField(db_column='Correo_Electronico', max_length=255, unique=True)),
                ('ubicacion', models.CharField(blank=True, db_column='Ubicacion', max_length=255, null=True)),
                ('fecha_hora_registro', models.DateTimeField(blank=True, db_column='Fecha_Hora_Registro', null=True)),
                ('id_usuario', models.ForeignKey(db_column='ID_Usuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='ID_Producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=255)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
                ('imagen', models.TextField(blank=True, db_column='Imagen', null=True)),
                ('fecha_registro', models.DateField(blank=True, db_column='Fecha_Registro', null=True)),
                ('unidad_de_medida', models.CharField(blank=True, max_length=2, null=True)),
                ('id_usuario', models.ForeignKey(db_column='ID_Usuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(db_column='ID_Pago', primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField(blank=True, db_column='Fecha_Pago', null=True)),
                ('metodo_pago', models.CharField(db_column='Metodo_Pago', max_length=13)),
                ('evidencia_pago', models.TextField(blank=True, db_column='Evidencia_Pago', null=True)),
                ('id_compra', models.ForeignKey(db_column='ID_Compra', on_delete=django.db.models.deletion.DO_NOTHING, to='Front.compra')),
                ('id_cuota', models.ForeignKey(db_column='ID_Cuota', on_delete=django.db.models.deletion.DO_NOTHING, to='Front.cuota')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='id_producto',
            field=models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.DO_NOTHING, to='Front.producto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_proveedor',
            field=models.ForeignKey(db_column='ID_Proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='Front.proveedor'),
        ),
    ]
