# Generated by Django 4.2 on 2024-12-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='correo_electronico',
            field=models.CharField(db_column='Correo_Electronico', max_length=255),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='dni_pasaporte',
            field=models.CharField(db_column='DNI_Pasaporte', max_length=50),
        ),
    ]
