# Generated by Django 4.2 on 2024-12-11 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0002_alter_proveedor_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='id_cuota',
            field=models.ForeignKey(blank=True, db_column='ID_Cuota', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Front.cuota'),
        ),
    ]
