# Generated by Django 4.2 on 2024-12-12 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Front', '0003_alter_pago_id_cuota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='id_producto',
            field=models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.CASCADE, to='Front.producto'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='id_proveedor',
            field=models.ForeignKey(db_column='ID_Proveedor', on_delete=django.db.models.deletion.CASCADE, to='Front.proveedor'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='id_compra',
            field=models.ForeignKey(db_column='ID_Compra', on_delete=django.db.models.deletion.CASCADE, to='Front.compra'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_compra',
            field=models.ForeignKey(db_column='ID_Compra', on_delete=django.db.models.deletion.CASCADE, to='Front.compra'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_cuota',
            field=models.ForeignKey(blank=True, db_column='ID_Cuota', null=True, on_delete=django.db.models.deletion.CASCADE, to='Front.cuota'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_usuario',
            field=models.ForeignKey(db_column='ID_Usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_usuario',
            field=models.ForeignKey(db_column='ID_Usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
