# Generated by Django 4.2 on 2024-12-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0004_alter_compra_id_producto_alter_compra_id_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='cuotas_pagadas',
            field=models.CharField(blank=True, db_column='Cuotas_Pagadas', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
