# Generated by Django 4.2 on 2024-12-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0005_cuota_cuotas_pagadas_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='evidencia_pago',
            field=models.ImageField(blank=True, null=True, upload_to='Evidencia_Pagos/'),
        ),
    ]
